version: '3'

services:
  db_postgres:
    networks:
      - nest
    restart: on-failure
    image: postgres:12.1-alpine
    container_name: 'postgres_nest'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD:docker
      - POSTGRES_DB=nest-db
    volumes:
      - './database/postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432

  api_node:
    build: .
    networks:
      - nest
    links:
      - db_postgres
    depends_on:
      - db_postgres
    container_name: 'node_nest'
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
    command: 'sh /usr/app/start.sh'

networks:
  nest: